# Generated by Django 4.1 on 2022-11-09 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="categories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="postCategory",
            field=models.ManyToManyField(
                through="news.PostCategory",
                to="news.category",
                verbose_name="Категория",
            ),
        ),
    ]
