# Generated by Django 4.1 on 2023-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_author_authoruser_en_us_author_authoruser_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="categoryType_en_us",
            field=models.CharField(
                choices=[("NW", "Новость"), ("AR", "Статья")],
                default="AR",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="categoryType_ru",
            field=models.CharField(
                choices=[("NW", "Новость"), ("AR", "Статья")],
                default="AR",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="dataCreation_en_us",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="dataCreation_ru",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post", name="text_en_us", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post", name="text_ru", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en_us",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ru",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
