# Generated by Django 4.1 on 2023-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_post_categorytype_en_us_post_categorytype_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en_us",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
