# Generated by Django 4.1 on 2023-01-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_category_name_en_us_category_name_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categoryType",
            field=models.CharField(
                choices=[("NW", "News"), ("AR", "Articl")], default="AR", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categoryType_en_us",
            field=models.CharField(
                choices=[("NW", "News"), ("AR", "Articl")],
                default="AR",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categoryType_ru",
            field=models.CharField(
                choices=[("NW", "News"), ("AR", "Articl")],
                default="AR",
                max_length=2,
                null=True,
            ),
        ),
    ]
