# Generated by Django 4.1 on 2023-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_post_categorytype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categoryType",
            field=models.CharField(
                choices=[("NW", "News"), ("AR", "Article")], default="AR", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categoryType_en_us",
            field=models.CharField(
                choices=[("NW", "News"), ("AR", "Article")],
                default="AR",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categoryType_ru",
            field=models.CharField(
                choices=[("NW", "News"), ("AR", "Article")],
                default="AR",
                max_length=2,
                null=True,
            ),
        ),
    ]
