# Generated by Django 4.1 on 2025-07-03 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0009_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="new_subscribers",
            field=models.ManyToManyField(
                related_name="categories",
                through="news.Subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="old_categories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
