# Generated by Django 4.1 on 2025-07-03 03:54
from django.conf import settings
from django.db import migrations


def transfer_data(apps, schema_editor):
    Category = apps.get_model('news', 'Category')
    User = apps.get_model('auth', 'User')
    Subscription = apps.get_model('news', 'Subscription')

    for category in Category.objects.all():
        for user in category.subscribers.all():
            Subscription.objects.get_or_create(
                user=user,
                category=category
            )


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0009_subscription"),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]