# Generated by Django 4.1 on 2025-07-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_category_new_subscribers_alter_category_subscribers"),
        ("news", "0011_transfer_subscriptions"),
    ]

    operations = []
